name: Deploy Frontend

on:
  workflow_dispatch:
  
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install yarn
        run: |
          cd my-blog
          npm install yarn -g

      - name: Clean up node_modules and .next
        run: |
          echo "Cleaning up node_modules and .next..."
          cd my-blog
          Remove-Item -Recurse -Force node_modules
          Remove-Item -Recurse -Force .next

      - name: Install dependencies
        run: |
          cd my-blog
          yarn install
          
      - name: Build my-blog
        run: |
          cd my-blog
          yarn build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          url: ${{ secrets.PAGE_URL }}
